apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
spec:
  replicas: 2
  selector:
    app: my-app-rc
  template:
    metadata:
      name: my-app-rc
      labels:
        app: my-app-rc
    spec:
      containers:
      - name: my-nginx
        image: nginx
        env:
          - name: MYENV
            value: blahblah
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
