apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app-container
        image: kodekloud/examplevotingapp_result:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "60m"
        ports:
          - containerPort: 80