apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app-container
        image: kodekloud/examplevotingapp_vote:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
          - containerPort: 80