apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app-container
        image: kodekloud/examplevotingapp_worker:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"